### PR TITLE
handle multiples character in flag parsing

### LINKED ISSUE #108: Failed to parse french hunspell dictionary
In french dictionary, flags can have multiple characters.
Ex:
`
NEEDAFFIX ()
FORBIDDENWORD {}
CIRCUMFIX **
KEEPCASE ||
NOSUGGEST --
`

and it's not correctly handeled

### PR DESCRIPTION
**Pull request by gwen-lg**
flag allow multiple characters, but only the first one was take.
In fr hunspell dictionary, `()`, `{}`, `||`, `--` are used as flags.
This change create a String with all characters, not only the first on.
Without this change, the french dictionary failed to load.

I have tested than `en` dictionary always load, but I haven't particularly tested it more.

Fixes #108

### CODE REVIEW

**Comment by tgross35** [comment]
Thanks for the PR! Most of the clippy errors aren't from this (fixed in https://github.com/pluots/zspell/pull/110). Could you rebase?

Also this should have a regression test, do you mind adding something in https://github.com/pluots/zspell/blob/2deff3a2d128b94e534da3fdca1f1858fac7cc0c/zspell/src/affix/tests_parse.rs?

**Comment by tgross35** [comment]
Nevermind, I'll add the test separately :). Thanks!

**Comment by gwen-lg** [comment]
ok, as you want, I was looking to do it :)
Thank you as well.

**Comment by gwen-lg** [comment]
Not sure if it's the good way to write it (I don't know enough the code), but I do this :
```rust
#[test]
fn test_line_key_parser_long() {
    let s = "NEEDAFFIX ()";
    assert_eq!(
        line_key_parser(s, "NEEDAFFIX", |val| Ok(AffixNode::AfxNeededFlag(
            val.to_owned()
        ))),
        Ok(Some((AffixNode::AfxNeededFlag("()".to_owned()), "", 0)))
    );
}
```

**Comment by tgross35** [comment]
The issue is actually a bit deeper, it comes from the `FLAG long` directive (flags are two characters) which isn't yet tested. So I think you will probably have incorrect answers elsewhere. I am taking a look at that now.

**Review by Yedfree — APPROVED** [review]

**Pull request merged**
